version: 2
project_name: tg
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/tg
    ldflags:
      - -s -w
      - -X main.buildVersion={{ .Version }}
      - -X main.buildCommit={{ .Commit }}
      - -X main.buildDate={{ .Date }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore(dep):'
      - '^test:'
